### ISSUE TITLE
Tried to build with telegram

### ISSUE THREAD

**Issue by F1reworks10** [3ct0s/disctopia-c2#101]
[+] Building backdoor...
Traceback (most recent call last):
  File "C:\Users\georg\Desktop\disctopia-c2\builder.py", line 256, in <module>
    subprocess.call(compile_command)
  File "C:\Users\georg\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\georg\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\georg\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by atanu2679** [comment]
> [+] Building backdoor... Traceback (most recent call last): File "C:\Users\georg\Desktop\disctopia-c2\builder.py", line 256, in subprocess.call(compile_command) File "C:\Users\georg\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 345, in call with Popen(*popenargs, **kwargs) as p: File "C:\Users\georg\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\georg\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] The system cannot find the file specified

you did something wrong, mine is work perfect bro..
