### ISSUE TITLE
Unable to create the backdoor -

### ISSUE THREAD

**Issue by OwxnBlxd** [3ct0s/disctopia-c2#24]
[+] Building the Backdoor
[+] Please wait...

Traceback (most recent call last):
  File "C:\Users\Jord\Desktop\disco test\builder.py", line 179, in <module>
    builder.build()
  File "C:\Users\Jord\Desktop\disco test\builder.py", line 43, in build
    self.compile()
  File "C:\Users\Jord\Desktop\disco test\builder.py", line 50, in compile
    subprocess.call(compile_command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

-- I am on windows 10 and have all of the necessary addons for python - I have noticed other people having the same problem - it then outputs a python file instead of an exe

**Comment by 3ct0s** [comment]
It appears that you are not following the instructions. You are supposed to use the python that comes with the tool which is python 3.8.9. You get that after running the setup PowerShell command. Please follow the instructions [here](https://github.com/3ct0s/disctopia-c2/tree/main/inst)

**Comment by OwxnBlxd** [comment]
I have the correct version of python - it is still not working

**Comment by 3ct0s** [comment]
Can you please confirm that you did in fact use the commands stated in the instruction to run the builder? Also, did you complete the setup without any errors?
Thanks.

**Comment by OwxnBlxd** [comment]
![image](https://user-images.githubusercontent.com/53382312/155806619-bd515c30-78ab-4cf2-a10d-282cc012fc96.png)

**Comment by 3ct0s** [comment]
Here is a possible fix to the issue: 
1. Manually run the python-3.8.9.exe file and click on Uninstall (If it gives you an error move to the next step)
2. Again manually run the python-3.8.9.exe file and Click on Repair.
3. After the repair is done you should be able to run the PowerShell command again with no issues.

**Comment by OwxnBlxd** [comment]
Thank you it is fixed now

**Comment by 3ct0s** [comment]
Did you manage to create a backdoor successfully? Let me know!

**Comment by OwxnBlxd** [comment]
Yes, it works - I think it was because I had multiple versions of python installed
