### ISSUE TITLE
Fetch data error 

### ISSUE THREAD

**Issue by Meep123as** [3ct0s/disctopia-c2#40]
Traceback (most recent call last):
  File "builder.py", line 170, in <module>
    fetch(list)
  File "builder.py", line 98, in fetch
    data = json.load(file)
  File "C:\Users\k\Downloads\disctopia-c2\python3.8.9\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\k\Downloads\disctopia-c2\python3.8.9\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\k\Downloads\disctopia-c2\python3.8.9\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\k\Downloads\disctopia-c2\python3.8.9\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 3 (char 4)

How do i fix this everything is installed

**Comment by Meep123as** [comment]
nothing is modified
