### ISSUE TITLE
builder error

### ISSUE THREAD

**Issue by LendaMarian** [3ct0s/disctopia-c2#62]
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\disctopia-c2-main\builder.py", line 204, in <module>
    builder.build()

  File "C:\Users\hp\Desktop\disctopia-c2-main\builder.py", line 49, in build
    self.compile()

  File "C:\Users\hp\Desktop\disctopia-c2-main\builder.py", line 60, in compile
    subprocess.call(compile_command)

  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:

  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

**Comment by 3ct0s** [comment]
This error usually means that the custom python version did not install properly. Are you using your own python version to run this?

**Comment by 3ct0s** [comment]
Ok, the issue here is that you are not using the version needed from the tool. Please use the instructions from the Wiki to install the needed requirements and the Build guide on how to build the EXE

**Comment by LendaMarian** [comment]
python is incomplete downloading though.

**Comment by LendaMarian** [comment]
i am using like this 

C:\Users\hp\AppData\Local\Programs\Python\Python38\python.exe .\builder.py

**Comment by 3ct0s** [comment]
The tool uses a virtual environment for python. You should run the setup.ps1 script to set everything up and then run the builder using venv\Scripts\python.exe builder.py while being in the disctopia-c2 dir.

**Comment by faiqff** [comment]
its same for me tf
