### ISSUE TITLE
CV2 error

### ISSUE THREAD

**Issue by FreezyKaif** [3ct0s/disctopia-c2#63]
Traceback (most recent call last):
  File "Test.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "importlib\__init__.py", line 127, in import_module
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "cv2\__init__.py", line 76, in bootstrap
    raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.

**Comment by 3ct0s** [comment]
This error has now been resolved with version 1.1.9
[](https://github.com/3ct0s/disctopia-c2/releases/tag/v1.1.9)
