### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by gogo0418** [3ct0s/disctopia-c2#72]
Traceback (most recent call last):
  File "C:\Users\sadd\Desktop\disctopia-c2-main\builder.py", line 204, in <module>
    builder.build()
  File "C:\Users\sadd\Desktop\disctopia-c2-main\builder.py", line 49, in build
    self.compile()
  File "C:\Users\sadd\Desktop\disctopia-c2-main\builder.py", line 60, in compile
    subprocess.call(compile_command)
  File "C:\Program Files (x86)\Python36-32\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files (x86)\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)

**Comment by Ron-zs** [comment]
we have the same question

**Comment by Ron-zs** [comment]
I get the solution in the completed problems ,you can replace the function which name is Buider.compile in builder.py 
`def compile(self):
        print(self.BACKDOOR_NAME)
        compile_command = f"pyinstaller --onefile --noconsole --icon=img/exe_file.ico {self.BACKDOOR_NAME}.py"
        subprocess.call(compile_command, shell=True)
        try:
            os.remove(self.BACKDOOR_NAME+".py");os.remove(self.BACKDOOR_NAME+".spec")
        except FileNotFoundError:
            pass`
