### ISSUE TITLE
discord.errors.LoginFailure: Improper token has been passed..(HOW TO FIX?)

### ISSUE THREAD

**Issue by BLEKERS** [3ct0s/disctopia-c2#91]
Traceback (most recent call last):
  File "discord\http.py", line 300, in static_login
  File "discord\http.py", line 254, in request
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "TEST.py", line 599, in <module>
  File "discord\client.py", line 723, in run
  File "discord\client.py", line 702, in runner
  File "discord\client.py", line 665, in start
  File "discord\client.py", line 511, in login
  File "discord\http.py", line 304, in static_login
discord.errors.LoginFailure: Improper token has been passed..

**Comment by BLEKERS** [comment]
when I run the payload its shows this one 
![image](https://user-images.githubusercontent.com/88395850/214600215-1ea433fe-6a3b-440f-a998-68cb53c40dfa.png)

**Comment by BLEKERS** [comment]
when I run the payload its shows this one 
![paytload](https://user-images.githubusercontent.com/88395850/214601145-5fa0b44a-16b4-4f70-ae61-ebdef4fef5e7.png)
